### ISSUE TITLE
Automatically add **FREE if converting all rows ( was: Comments on F-Spec)

### ISSUE THREAD

**Issue by SJLennon** [BrianGarland/vscode-rpgfree#23]
If I convert this:
`     fTGTSTKP   UF A E           K DISK    rename(TGTSTKF:TGTSTKX)              `
It comes out like this:
`        Dcl-F TGTSTKP Usage(*Update:*Delete:*Output) Keyed rename(TGTSTKF:TGTSTKX);`

It looks right, but if you try to compile it you get: 
_RNF5501: The comment entry on a free-form specification is not valid. (20)_
This causes the following line to mess up on the compile with:
_RNF0312 20 a      000600  A right parenthesis is expected but is not found._

If I go back to green screen and prompt the D-spec I can enter a comment:
![image](https://user-images.githubusercontent.com/67484051/142060225-9ea90ad9-7941-4322-9d11-e927cce1f3bf.png)
Which looks like this in VS Code:
`     fTGTSTKP   UF A E           K DISK    rename(TGTSTKF:TGTSTKX)              My primary input`
Which converted is:
`        Dcl-F TGTSTKP Usage(*Update:*Delete:*Output) Keyed rename(TGTSTKF:TGTSTKX); //My primary input`
 The comment is at column 81 in the original.  In the conversion at col 81 is "X); //My primary input".
If I put the rename(TGTSTKF:TGTSTKX); on a new line it compile.
Apparently anything past column 80 on a dcl_f is a comment.  I haven't been able to find this in IBM documentation, though.

**Comment by BrianGarland** [comment]
Do you have **FREE at the top of your code?  

That's one thing that the conversion never added automatically.

**Comment by SJLennon** [comment]
Well duh!  **free fixed the problem.  My fault.  Sorry...

(I guess that if all code was being converted it would be nice to put a **free at the top.)

**Comment by BrianGarland** [comment]
0.0.25 now adds **FREE if you do not select any rows to convert because it converts all rows.
