### ISSUE TITLE
Z-Add and repeated cases

### ISSUE THREAD

**Issue by RoySpino** [BrianGarland/vscode-rpgfree#24]
Z-Add should be an assignment.
Also try adding this dictionary to simplify  IFXX, DOWXX etc.

 let D_rpg3_OP = {
      "EQ": "=",
      "NE": "<>",
      "GT": ">",
      "LT": "<",
      "GE": ">=",
      "LE": "<="};

...
case 'IFGT':
case 'IFLE':
    output.value = `If ` + factor1 + ` ` + D_rpg3_OP [plainOp.substr(2,2)] + ` ` + factor2;

**Comment by BrianGarland** [comment]
Z-ADD and Z-SUB will be updated in 0.0.23

**Comment by BrianGodsend** [comment]
This issue appears to have been resolved.

Can this issue be closed?
