### ISSUE TITLE
Source line conditioning indicator

### ISSUE THREAD

**Issue by Hadkins2** [BrianGarland/vscode-rpgfree#29]
Converting some old code and the source line has a conditioning indicator in columns 9-11.

![image](https://user-images.githubusercontent.com/95584606/149578642-f0c4fb82-d66b-4cd3-af3e-e1283cedd409.png)

When using Convert to Free Format, the converted code will sometimes drop the indicator in 9-11.  Other times, it adds an if with the indicator around it as expected, but with the same source line inside the new if and again outside the if.  I am concerned that when converting a large section of code, the lost indicator would be easy to over look.  Where it adds a copy of the conditioned code outside the new If statement might be easy to catch.  

Before and after conversion:

![image](https://user-images.githubusercontent.com/95584606/149585829-eedb60f8-05d9-455a-9f37-cb003af887fa.png)

Thanks,

Howard

**Comment by m-tyler** [comment]
I am noticing a similar issue for level break (CLx) source lines.  I would suggest leaving these lines alone.

**Comment by m-tyler** [comment]
I confirm the fix works for me.

**Comment by Hadkins2** [comment]
Thank you!  Much appreciated. 

Howard
