### ISSUE TITLE
SQL conversion to free after new release

### ISSUE THREAD

**Issue by rustygad** [BrianGarland/vscode-rpgfree#3]
Overall it did a pretty good job.

1. Exec SQL is missing at the beginning.
2. Injecting blank lines. 
3. Would be nice if semicolon could be appended to last statement.

Original statements:

     C/Exec SQL
     C+       DECLARE DBCURSOR CURSOR FOR
     C+        SELECT *
     C+          FROM GLCOA
     C+         WHERE GCLVL1 = :i_GCLVL1
     C+           AND GCLVL2 = :i_GCLVL2
     C+           AND GCLVL3 = :i_GCLVL3
     C+           AND GCACTY = :i_GCACTY
     C+           AND GCACCT = :i_GCACCT
     C+           FOR UPDATE
     C/End-Exec
     C/Exec SQL
     C+        Open DbCursor
     C/End-Exec
     C/Exec SQL
     C+        FETCH NEXT
     C+         FROM DBCURSOR
     C+         INTO :c_GCLVL1,
     C+              :c_GCLVL2,
     C+              :c_GCLVL3,
     C+              :c_GCACTY,
     C+              :c_GCACCT,
     C+              :c_GCACNO,
     C+              :c_GCDESC,
     C+              :c_GCTYPE,
     C+              :c_GCTYP2,
     C+              :c_GCSLYN,
     C+              :c_GCSTAT
     C/End-Exec

Converted to:

              DECLARE DBCURSOR CURSOR FOR
                                      
        
                 FROM GLCOA
                                                    
                WHERE GCLVL1 = :i_GCLVL1
                                       
                  AND GCLVL2 = :i_GCLVL2
                                       
                  AND GCLVL3 = :i_GCLVL3
                                       
                  AND GCACTY = :i_GCACTY
                                       
                  AND GCACCT = :i_GCACCT
                                       
                  FOR UPDATE
                                                   
        ;

               Open DbCursor
                                                   
        ;

        
                FROM DBCURSOR
                                                  
                INTO :c_GCLVL1,
                                                
                     :c_GCLVL2,
                                                
                     :c_GCLVL3,
                                                
                     :c_GCACTY,
                                                
                     :c_GCACCT,
                                                
                     :c_GCACNO,
                                                
                     :c_GCDESC,
                                                
                     :c_GCTYPE,
                                                
                     :c_GCTYP2,
                                                
                     :c_GCSLYN,
                                                
                     :c_GCSTAT
                                                 
        ;

**Comment by BrianGarland** [comment]
Oh, duh!  (EXEC SQL missing).   I will fix that.  

The extra blank lines are odd.  

I'm not sure if I can move that semi-colon.  I am hoping to but it would require some kind of look ahead in the logic.

**Comment by BrianGarland** [comment]
@rustygad version 0.0.6 should fix these issues.  Please let me know what you think of it.

**Comment by rustygad** [comment]
I’ll bring in the latest version and give is a test.

**Comment by BrianGarland** [comment]
Included in version 0.0.6
