### ISSUE TITLE
Primary/Secondary I/O processed file spec lines need to remain as is when converting

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#30]
If I convert a program with an `  FFILE      P...` source line the line gets converted to Dcl-F .  This is incorrect and the conversion tool should not convert them.

**Comment by m-tyler** [comment]
If the source has level break (CLx) indicator source lines, the Lx indicator is removed similar to issue #29.  I would suggest leaving these lines alone.

**Comment by BrianGarland** [comment]
The Primary and Secondary file issue will be fixed in release 0.0.32

The level (CLx) fix was previously done in 0.0.23.
