### ISSUE TITLE
RPG fixed asterisk (*) comments with interior spaces converted wrong

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#31]
When converting a fixed format RPGLE program with asterisks in column 7, the comments with spaces between the asterisk and any words on the line have the "extra" interior spaces are removed.

`      *-----------------------------------------------------------------------`
`      *    MODIFICATIONS:                                                                         `
`      *-----------------------------------------------------------------------`
to 
`        //-----------------------------------------------------------------------`
`        //MODIFICATIONS: `
 `       //-----------------------------------------------------------------------`

Plus, comments are not converted as a standalone conversion item.  The tool apparently needs actual RPG code to activate the convert.

**Comment by BrianGarland** [comment]
Will be fixed in 0.0.23
