### ISSUE TITLE
Converted RPG Fixed  DS code does not include End-Ds; if last DS in conversion set

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#32]
Before conversion
![image](https://user-images.githubusercontent.com/1353665/153241350-8409585e-4655-48dc-b6f6-0fc68dca6458.png)

After conversion
![image](https://user-images.githubusercontent.com/1353665/153241432-0be47000-a0c9-4ff6-ba08-f8e2e0e1167e.png)

If you select additional code to convert.
Before
![image](https://user-images.githubusercontent.com/1353665/153241521-b7c1e0af-508f-4dd9-b65e-f1e710fca681.png)

After
![image](https://user-images.githubusercontent.com/1353665/153241560-a1d01e58-8ece-47f5-8442-3045e473d142.png)

**Comment by BrianGodsend** [comment]
Sorry for my multiple commits related to this issue.  I kept thinking I was doing something wrong in my commit message as the issues were linked, but not closed.  I _think_ linking to an issue will auto-close only if you are the creator of the issue.  So, the pull request #79 from the [BrianGodsend/vscode-rpgfree](https://github.com/BrianGodsend/vscode-rpgfree "BrianGodsend fork") fork does fix this issue.

**Comment by BrianGarland** [comment]
Tested with 0.0.30 and this appears to convert correctly.
