### ISSUE TITLE
Conversion of sub routine duplicates last two lines in error

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#33]
I notice this when the only code is program calls.    I have the sample sub-routine defined before *INZSR at the end of the program source.   If I convert one or both they both convert wrong.  You can also notice that one of the calls is missing in each sub-routine. 

Before
![image](https://user-images.githubusercontent.com/1353665/153242252-e47256dd-c7e3-49a9-b3ec-af937a2009b4.png)

After
![image](https://user-images.githubusercontent.com/1353665/153242029-32e01a24-7de8-4e0c-a05f-e154a0ed282c.png)

**Comment by BrianGarland** [comment]
It is still broken but in a different way. 

It only has one ENDSR but it loses the first call.

**Comment by m-tyler** [comment]
Well, I am trying to convert as many of these as I can when I encounter them.   Your extension will hopefully, one day, be useless for me.   It save me a TON of work as it is.  

Big thanks for the time savings.

**Comment by BrianGarland** [comment]
This will be fixed in 0.0.32
