### ISSUE TITLE
Imbedded free format RPG is not indented like converted code.

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#34]
I have this bit of code
![image](https://user-images.githubusercontent.com/1353665/153250357-18142b94-461a-4d25-9085-c3e5a7e38ea4.png)

This is what it looks like after conversion.
![image](https://user-images.githubusercontent.com/1353665/153250494-4b28760d-198f-4260-99a9-5f2f2e224708.png)

Should the conversion tool indent existing free formatted code?  I say yes.

**Comment by SJLennon** [comment]
FWIW:  Indenting is in the vscode-rpgle extension.

**Comment by BrianGarland** [comment]
This will not be fixed in this tool.  I suggest using the RPGLE Languange linter to fix the indentation of the entire file after converting.
