### ISSUE TITLE
PROCPTR is not converted to POINTER(*PROC)

### ISSUE THREAD

**Issue by AG1965** [BrianGarland/vscode-rpgfree#36]
When converting a fixed format like

`    D PtrCallback     S               *   PROCPTR`

to free format, it is converted to

`       Dcl-S PtrCallback  Pointer    PROCPTR;`

instead of 

`       Dcl-S PtrCallback  Pointer(*PROC);`

**Comment by BrianGarland** [comment]
Will be in next release

**Comment by BrianGarland** [comment]
I'm not sure what version this was fixed in but it does work as of 0.0.22
