### ISSUE TITLE
Stand alone dates with DATFMT() keywords are converting incorrectly

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#38]
I am at version  0.0.21 and I am seeing this conversion problem.   The TIMFMT() also convert incorrectly. 

Before:
```     D DATE_ISOx       S               D   DATFMT(*ISO)
     D DATE_USAx       S               D   DATFMT(*USA)       
```
After:
```
        Dcl-S DATE_ISOx    Date       DATFMT(*ISO);
        Dcl-S DATE_USAx    Date       DATFMT(*USA);
```

Should be:
```
        Dcl-S DATE_ISOx    Date(*ISO);
        Dcl-S DATE_USAx    Date(*USA);
```

**Comment by BrianGarland** [comment]
will be fixed in 0.0.22

**Comment by m-tyler** [comment]
I realize I never added the time keyword to this or as a new issue.  Please look for those also.   Thanks.

**Comment by BrianGarland** [comment]
I had thought of TIMFMT but after fixing DATFMT forgot.  Thanks for the reminder!
