### ISSUE TITLE
External data structure does not convert correctly

### ISSUE THREAD

**Issue by BrianGarland** [BrianGarland/vscode-rpgfree#4]
Fixed form: D APBATREC E DS EXTNAME(APBAT)

Free form: DCL-DS APBATREC EXTNAME(APBAT);

Should be: DCL-DS APBATREC EXTNAME('APBAT');

**Comment by BrianGarland** [comment]
Included in version 0.0.7

**Comment by BrianGarland** [comment]
Included in version 0.0.7

**Comment by SJLennon** [comment]
More feedback:
This:

```
      *=== IPRUCALCP Data Structure ==================================
     d IPRUCALCP     e ds                  extname(MXLNHSPE)

```
  
When converted gives this:
```

        //=== IPRUCALCP Data Structure ==================================
        Dcl-DS IPRUCALCP  extname('MXLNHSPE');

```


but it needs an END-DS, otherwise the code following it gets lumped in.   

@BrianGarland

**Comment by BrianGarland** [comment]
0.0.9 published with this fix
