### ISSUE TITLE
MOVE with dates not converting correctly

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#40]
I am using version 0.0.21.
When I convert this line;
```      
      C     *ISO0         MOVE      DATE_ISO      P06EFFDT
```
It shows up like this.
```
        P06EFFDT = DATE_ISO;
```
It should appear as 
```
      P06EFFDT = %CHAR( DATE_ISO :*ISO0 );
```

The hard part about this one is knowing the data type of the result variable without doing a complete code inspection.    I would think the best solution for a case like this is to leave it alone.

**Comment by BrianGarland** [comment]
Do to the complexities of determining data types and lengths MOVE and MOVEL are no longer supported.
