### ISSUE TITLE
Incorrect conversion of continued literals

### ISSUE THREAD

**Issue by JonFP** [BrianGarland/vscode-rpgfree#43]
In attempting to convert Scott Klement's Base64 routines I encountered multiple issues - mostly concerning conversion of continued literals.

For example this:
```
     H COPYRIGHT('Copyright (c) 2005-2007 Scott C. Klement.  All rights +
     H reserved.  A member called "LICENSE" was included with this +
     H distribution, and contains important license information.')
```
Converts incorrectly to multiple Ctl-Opt lines like this:
```
Ctl-Opt COPYRIGHT('Copyright (c) 2005-2007 Scott C. Klement.  All rights +;
Ctl-Opt reserved.  A member called "LICENSE" was included with this +;
Ctl-Opt distribution, and contains important license information.');
```

I have attached copies of the files required for compiling this code.
[base64_h.rpgle.txt](https://github.com/BrianGarland/vscode-rpgfree/files/8720541/base64_h.rpgle.txt)
[base64r4.rpgle.txt](https://github.com/BrianGarland/vscode-rpgfree/files/8720542/base64r4.rpgle.txt)

**Comment by BrianGarland** [comment]
0.0.31 should resolve this issue with H-Specs.
