### ISSUE TITLE
rpgfree doesn't run anymore

### ISSUE THREAD

**Issue by karlxfritz** [BrianGarland/vscode-rpgfree#49]
Since some days I get no option to convert selected statements with a right click.

VS Code 1.72.2
Code for IBM i v1.5.17

**Comment by worksofliam** [comment]
@karlxfritz What version of vscode-rpgfree are you running?

**Comment by karlxfritz** [comment]
Hi,

 

Sorry that I didn't mention it.

v0.0.21 – think it's the newest.

 

Karl

Von: barry ***@***.*** 
Gesendet: Montag, 17. Oktober 2022 15:51
An: BrianGarland/vscode-rpgfree
Cc: karlxfritz; Mention
Betreff: Re: [BrianGarland/vscode-rpgfree] rpgfree doesn't run anymore (Issue #49)

 

@karlxfritz <https://github.com/karlxfritz>  What version of vscode-rpgfree are you running?

**Comment by BrianGarland** [comment]
@karlxfritz Is this still a problem?  I'm not sure why you wouldn't have the menu option.

**Comment by karlxfritz** [comment]
Hi Brian,

 

the problem still exists.

I had a situation, when all worked well.

But now, I can select the statements, click right and nothing happens.

 

Example:



 

This is a part of the source and you see, the convert item is missing.

I uninstalled/installed the extension. Maybe it's an issue of Code for IBMi (Liam).

 

All program parts are on the newest version. IBM OS V7.5.

 

Thanks,

Karl

 

Von: Brian Garland ***@***.*** 
Gesendet: Montag, 24. Oktober 2022 16:59
An: BrianGarland/vscode-rpgfree
Cc: karlxfritz; Mention
Betreff: Re: [BrianGarland/vscode-rpgfree] rpgfree doesn't run anymore (Issue #49)

 

@karlxfritz <https://github.com/karlxfritz>  Is this still a problem? I'm not sure why you wouldn't have the menu option.

**Comment by karl-fritz** [comment]
Close this issue. If I do a right mouse click, I need the submenu at the bottom of the menu and the i find the conversion select. 

Runs ok, thought i can do that on the first click.
