### ISSUE TITLE
PLIST does not convert

### ISSUE THREAD

**Issue by BrianGarland** [BrianGarland/vscode-rpgfree#5]
```
 C     *entry        plist      
 C                      parm                    var11 
 C                      parm                    var12 

```
These lines do not change when selected for conversion.

**Comment by BrianGarland** [comment]
This was causing the extension to fail and nothing to be converted.  0.0.7 fixes that failure but this does not convert a PLIST yet.

**Comment by SJLennon** [comment]
Feedback:

PLIST no longer stops the conversion, but it totally removes the PLIST code.  Not sure that is good-I think I would opt to leave the original code in there, if possible.

Given this:
```
     d EofIn           s               n

     c     *entry        plist
     c                   parm                    pClass
     c                   parm                    pRegion
     c                   parm                    pRetCode

     c                   eval      *INLR = *ON
```

When converted it give this:

```

        Dcl-S EofIn        Ind;


        *INLR = *ON;


```
@BrianGarland

**Comment by BrianGarland** [comment]
My intent is for the conversion to work.  I needed it to not break the entire project as a start.

**Comment by BrianGarland** [comment]
I've updated the code to just ignore *ENTRY PLIST for now. 

0.0.9 published with this fix

**Comment by devinhh** [comment]
Are there any plans to get this working to convert the *ENTRY PLIST ?
