### ISSUE TITLE
prototype not converted correctly - missing 'end-pr'

### ISSUE THREAD

**Issue by JDubbTX** [BrianGarland/vscode-rpgfree#54]
When converting a file that contains a single prototype in it, end-pr is not added at the end.

![image](https://user-images.githubusercontent.com/56802156/203342370-c610950f-5408-4233-bb7a-84e4b7d68a7c.png)
![image](https://user-images.githubusercontent.com/56802156/203342397-fea26391-e8f4-4b30-8e20-13c18958e88b.png)

**Comment by BrianGarland** [comment]
Were you just converting the prototype, or did it include code following the prototype?  I think there is an issue with adding the "end-xx" codes if there is nothing following it in the conversion.

**Comment by BrianGarland** [comment]
@JDubbTX I've tried your example from the highlighted box and the only way I can get it not to work is to not include the cr/lf at the end of the last line.   On the home page of this project, I note you have to include that.

**Comment by JDubbTX** [comment]
ok, yes there was no code after the prototype in every case.  I'll give it another shot.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
