### ISSUE TITLE
Convert indicator MOVE lines to free form EVAL 

### ISSUE THREAD

**Issue by m-tyler** [BrianGarland/vscode-rpgfree#64]
For situations where the items are of a known type just by looking at the source line please convert them.

Please convert `MOVE      *OFF          *IN98` type of statements into `*IN98 = *OFF;`
Please convert `MOVE      *OFF          INEMP_NOTZERO` type of statements into `INEMP_NOTZERO = *OFF;`

**Comment by BrianGarland** [comment]
Previously fixed.  Working in 0.0.34 based on test case C/022-move_ind
