### ISSUE TITLE
How much can be converted?

### ISSUE THREAD

**Issue by getfoundational** [BrianGarland/vscode-rpgfree#7]
Hello,

I've just recently found the VS extension, Code for IBM i.  While searching for it, I found your extension too and installed it.  I opened a fixed format program to convert as a test.  It looks like I can convert portions of the code but when selecting the entire program, it does not convert.

Is there a limit as to how much you can convert at a time?

I can segment my conversion, no problem, but was curious in case I was missing something.

Thank you.

**Comment by BrianGarland** [comment]
I know that rpgfreeweb (which is what this is based on had limitations.  I'll try to find why there is a limit and if it cannot be changed at least document it.

**Comment by getfoundational** [comment]
Awesome. Thanks for checking in to it.

**Comment by BrianGarland** [comment]
@getfoundational 

I just converted a 12000 line program and it converted it all.  I wonder if past problems with the extension caused your problem.  

Could you try this again and if it fails let me know how big the program was.

**Comment by getfoundational** [comment]
Thank you.

I just was able to convert a large program as well so perhaps I was just doing something wrong.

Another sort of related question.  When trying to right click to convert, that option is no longer present.  I need to right click and choose "Command Palette" and then find the convert to free command that way.

Any idea why it disappeared from the default right click menu?  I tried removing and re-installing the extension but that did not fix it.

Thank you again,

**Comment by BrianGarland** [comment]
There was a change to hide the menu option if you are not editing rpgle or sqlrpgle source.  

Is the type attribute for your source one of those?  Do you have the latest Code for IBM i?

**Comment by getfoundational** [comment]
Source type is .rpgle.  I did and updated check on VS Code and there were none for it and none of the extensions say they need an update either.  I think those check automatically so I assume they are updated fully.

**Comment by worksofliam** [comment]
When you have your RPG source open, do you have the language mode set to RPGLE?

![Screenshot 2021-11-09 at 8 26 14 AM](https://user-images.githubusercontent.com/3708366/140932221-1870a000-a9b7-4997-86bf-d74e0fd62318.png)

**Comment by getfoundational** [comment]
Thank you for the tip!

Mine is coming up as RPG and not RPGLE.  I forced a change to RPGLE and then it worked (among other things like more code highlighting too).

I closed the member and re-opened it though and it auto-detected to just plain RPG again.

Any idea why it might do that?

Thank you again.

**Comment by worksofliam** [comment]
@getfoundational You likely have two conflicting language extensions for RPGLE.

* https://marketplace.visualstudio.com/items?itemName=barrettotte.ibmi-languages
* https://marketplace.visualstudio.com/items?itemName=NielsLiisberg.RPG

**Comment by getfoundational** [comment]
You are correct.  I have both installed.  I was not aware they conflicted with one another.
