### ISSUE TITLE
Auto Data Area Data Structures Have Duplicate DtaAra Keywords

### ISSUE THREAD

**Issue by BrianGodsend** [BrianGarland/vscode-rpgfree#93]
When the declaration of an auto-data-area data structure (coded with a U) include the `DTAARA` keyword, the resulting free form declaration has two `DTAARA` keywords.  The fist keyword is the `DtaAra(*AUTO)` and the second is the keyword from the original line of source.  When converting an auto-data-area data structure, the *AUTO option of the `DTAARA` keyword must be placed in the existing definition, if any.

> [!NOTE]
> The output below also demonstrates the issue addressed by issue [#92]; where the `*VAR` option is not removed from the `DTAARA` keyword.

For example:

```RPGLE
     d @DTAARANAME     c                   'QTEMP/MYDTAARA'
     d dtaAraDs       uds                  dtaara(*VAR: @DTAARANAME)
     d  fld1                          1a
     c                   eval      *inLR = *ON
     c                   return
```

Is incorrectly converted as:

```RPGLE
**FREE
       Dcl-C @DTAARANAME 'QTEMP/MYDTAARA';
       Dcl-DS dtaAraDs  DtaAra(*AUTO) dtaara(*VAR: @DTAARANAME);
         fld1           Char(1);
       End-DS;
       *inLR = *ON;
       Return;
```

The expected output is:

```RPGLE
**FREE
       Dcl-C @DTAARANAME 'QTEMP/MYDTAARA';
       Dcl-DS dtaAraDs                dtaara(*AUTO: @DTAARANAME);
         fld1           Char(1);
       End-DS;
       *inLR = *ON;
       Return;
```

**Comment by BrianGarland** [comment]
Will be fixed in 0.0.30
